#  **Topic:** 
# <center> **Hotel Booking Cancellation Prediction** </center>

<div class="alert alert-block alert-success">
    <b>Importing required Libraries and Dataset</b> 
    <br>
   </div>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

<div class="alert alert-block alert-success">
    <h1>1. Data Reading / Data Loading</h1>
</div>

#### Dataset: <a>https://www.kaggle.com/datasets/jessemostipak/hotel-booking-demand</a>

In [2]:
import pandas as pd
Dataset = pd.read_csv('hotel_bookings.csv')
Dataset

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,01/07/2015
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,01/07/2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,02/07/2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,02/07/2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,03/07/2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,06/09/2017
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,07/09/2017
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,07/09/2017
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,07/09/2017
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,07/09/2017

<div class="alert alert-block alert-success">
    <h1>2. EDA (Data Exploration)</h1>
</div>

In [3]:
Dataset.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01/07/2015
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01/07/2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,02/07/2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,02/07/2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,03/07/2015

In [4]:
Dataset.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,06/09/2017
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,07/09/2017
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,07/09/2017
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,07/09/2017
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,07/09/2017

## Rows & Column

In [5]:
print('rows:', Dataset.shape[0])
print('columns:', Dataset.shape[1])

rows: 119390
columns: 32

In [6]:
Dataset.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='str')

In [7]:
Dataset.shape

(119390, 32)

In [8]:
Dataset.count()

hotel                             119390
is_canceled                       119390
lead_time                         119390
arrival_date_year                 119390
arrival_date_month                119390
arrival_date_week_number          119390
arrival_date_day_of_month         119390
stays_in_weekend_nights           119390
stays_in_week_nights              119390
adults                            119390
children                          119386
babies                            119390
meal                              119390
country                           118902
market_segment                    119390
distribution_channel              119390
is_repeated_guest                 119390
previous_cancellations            119390
previous_bookings_not_canceled    119390
reserved_room_type                119390
assigned_room_type                119390
booking_changes                   119390
deposit_type                      119390
agent                             103050
company                             6797
days_in_waiting_list              119390
customer_type                     119390
adr                               119390
required_car_parking_spaces       119390
total_of_special_requests         119390
reservation_status                119390
reservation_status_date           119390
dtype: int64

In [9]:
Dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 37.9 MB

In [10]:
Dataset.nunique()

hotel                                2
is_canceled                          2
lead_time                          479
arrival_date_year                    3
arrival_date_month                  12
arrival_date_week_number            53
arrival_date_day_of_month           31
stays_in_weekend_nights             17
stays_in_week_nights                35
adults                              14
children                             5
babies                               5
meal                                 5
country                            177
market_segment                       8
distribution_channel                 5
is_repeated_guest                    2
previous_cancellations              15
previous_bookings_not_canceled      73
reserved_room_type                  10
assigned_room_type                  12
booking_changes                     21
deposit_type                         3
agent                              333
company                            352
days_in_waiting_list               128
customer_type                        4
adr                               8879
required_car_parking_spaces          5
total_of_special_requests            6
reservation_status                   3
reservation_status_date            926
dtype: int64

In [11]:
Dataset['agent'].nunique

<bound method IndexOpsMixin.nunique of 0           NaN
1           NaN
2           NaN
3         304.0
4         240.0
          ...
119385    394.0
119386      9.0
119387      9.0
119388     89.0
119389      9.0
Name: agent, Length: 119390, dtype: float64>

In [12]:
Dataset.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [13]:
Dataset.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [14]:
Dataset.dtypes

hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

<div class="alert alert-block alert-success">
    <h1>3. Data Pre-Processing</h1>
</div>

### Checking null values

In [15]:
Dataset.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

## Filling null values

In [16]:
num = Dataset['company'].mode()[0]
Dataset['company'] = Dataset['company'].fillna(num)

In [17]:
num = Dataset['children'].mode()[0]
Dataset['children'] = Dataset['children'].fillna(num)

In [18]:
num = Dataset['agent'].mode()[0]
Dataset['agent'] = Dataset['agent'].fillna(num)

In [19]:
num = Dataset['country'].mode()[0]
Dataset['country'] = Dataset['country'].fillna(num)

In [20]:
Dataset.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

### Check datatypes of all columns & change

In [21]:
Dataset.dtypes

hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

In [22]:
cols = ['agent', 'children', 'company']
Dataset[cols] = Dataset[cols].fillna(0).astype(int)

In [23]:
Dataset.dtypes

hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                            int64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                               int64
company                             int64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

In [24]:
columns_to_drop = ['company', 'agent', 'reservation_status', 'reservation_status_date']
Dataset.drop(columns=columns_to_drop, inplace=True)

In [25]:
Dataset.to_csv('cleaned_data.csv', index=False, header=True)

In [26]:
encoders = {}

def encodeCols(cols):
    for i in cols:
        # Har column ki unique values ka DataFrame banana
        value = pd.DataFrame({i: Dataset[i].unique()})
        LE = LabelEncoder()
        LE.fit(value[i])
        Dataset[i] = LE.transform(Dataset[i])
        encoders[i] = LE
columns_to_encode = [
    'hotel', 'arrival_date_month', 'meal', 'country', 
    'market_segment', 'distribution_channel', 'reserved_room_type', 
    'assigned_room_type', 'deposit_type', 'customer_type', 
     
]
encodeCols(columns_to_encode)
joblib.dump(encoders, "encoders.pkl")

['encoders.pkl']

In [27]:
Dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  int64
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  int64
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119390 non-null  int64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  int64
 13  country                         119390 non-null  int64
 14  market_segment                  119390 non-null  int64
 15  distribution_channel            119390 non-null  int64
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  int64
 20  assigned_room_type              119390 non-null  int64
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  int64
 23  days_in_waiting_list            119390 non-null  int64
 24  customer_type                   119390 non-null  int64
 25  adr                             119390 non-null  float64
 26  required_car_parking_spaces     119390 non-null  int64
 27  total_of_special_requests       119390 non-null  int64
dtypes: float64(1), int64(27)
memory usage: 25.5 MB

<div class="alert alert-block alert-success">
    <h1>Train-Test Splitting</h1>
</div>

In [28]:
X = Dataset.drop('adr', axis=1)  
y = Dataset['adr']

In [29]:
X.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests
0,1,0,342,2015,5,27,1,0,0,2,...,0,0,2,2,3,0,0,2,0,0
1,1,0,737,2015,5,27,1,0,0,2,...,0,0,2,2,4,0,0,2,0,0
2,1,0,7,2015,5,27,1,0,1,1,...,0,0,0,2,0,0,0,2,0,0
3,1,0,13,2015,5,27,1,0,1,1,...,0,0,0,0,0,0,0,2,0,0
4,1,0,14,2015,5,27,1,0,2,2,...,0,0,0,0,0,0,0,2,0,1

In [30]:
y.head()

0     0.0
1     0.0
2    75.0
3    75.0
4    98.0
Name: adr, dtype: float64

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
X_train.head()
y_train.head()

67702     189.00
115851    146.00
57345     259.00
11622      89.70
33333      42.43
Name: adr, dtype: float64

In [33]:
X_test.head()
y_test.head()

30946      66.8
40207      76.5
103708     60.0
85144      95.0
109991    108.0
Name: adr, dtype: float64

In [34]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(95512, 27) (95512,)
(23878, 27) (23878,)

<div class="alert alert-block alert-success">
    <h1>Model Application</h1>
</div>

In [35]:
print("--Training the Model using Random Forest Regressor--")

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

--Training the Model using Random Forest Regressor--

RandomForestRegressor(random_state=42)

In [36]:
import pickle
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("Model Saved Successfully")

Model Saved Successfully

In [37]:
import joblib
joblib.dump(model, "model.pkl")

['model.pkl']

In [39]:
#Testing/Predicting
y_pred = model.predict(X_test)

In [40]:
from sklearn.metrics import mean_squared_error, r2_score

print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

279.32432502740926
0.8778634451872055

<div class="alert alert-block alert-success">
    <h1>Model Accuracy</h1>
</div>

In [41]:
print(f"Model Accuracy (R2 Score): {r2_score(y_test, y_pred):.2%}")

Model Accuracy (R2 Score): 87.79%

<div class="alert alert-block alert-success">
    <h1> Application Phase</h1>
</div>

In [45]:
import pandas as pd
import numpy as np
import pickle
import joblib

model = joblib.load('model.pkl')
encoders = joblib.load('encoders.pkl')

def encode_cols(le, value):
    if value in le.classes_:
        return le.transform([value])[0]
    else:
        return -1

print("Enter Booking Details:")

user_input = {
    "hotel": input("Hotel (Resort Hotel / City Hotel): "),
    "lead_time": int(input("Lead Time: ")),
    "arrival_date_year": int(input("Arrival Year: ")),
    "arrival_date_month": input("Arrival Month: "),
    "arrival_date_week_number": int(input("Week Number: ")),
    "arrival_date_day_of_month": int(input("Day of Month: ")),

    "stays_in_weekend_nights": int(input("Weekend Nights: ")),
    "stays_in_week_nights": int(input("Week Nights: ")),

    "adults": int(input("Adults: ")),
    "children": int(input("Children: ")),
    "babies": int(input("Babies: ")),

    "meal": input("Meal (BB/HB/FB/SC): "),
    "country": input("Country: "),
    "market_segment": input("Market Segment: "),
    "distribution_channel": input("Distribution Channel: "),

    "is_repeated_guest": int(input("Repeated Guest (0/1): ")),
    "previous_cancellations": int(input("Previous Cancellations: ")),
    "previous_bookings_not_canceled": int(input("Previous Not Canceled: ")),

    "reserved_room_type": input("Reserved Room Type: "),
    "assigned_room_type": input("Assigned Room Type: "),

    "booking_changes": int(input("Booking Changes: ")),
    "deposit_type": input("Deposit Type: "),
    "days_in_waiting_list": int(input("Waiting Days: ")),

    "customer_type": input("Customer Type: "),
    "adr": float(input("ADR (Average Daily Rate): ")),

    "required_car_parking_spaces": int(input("Parking Spaces: ")),
    "total_of_special_requests": int(input("Special Requests: "))
}

categorical_cols = [
    'hotel', 'arrival_date_month', 'meal', 'country',
    'market_segment', 'distribution_channel',
    'reserved_room_type', 'assigned_room_type',
    'deposit_type', 'customer_type'
]

for col in categorical_cols:
    user_input[col] = encode_cols(encoders[col], user_input[col])

features = [
    'hotel', 'lead_time', 'arrival_date_year', 'arrival_date_month',
    'arrival_date_week_number', 'arrival_date_day_of_month',
    'stays_in_weekend_nights', 'stays_in_week_nights',
    'adults', 'children', 'babies', 'meal', 'country',
    'market_segment', 'distribution_channel', 'is_repeated_guest',
    'previous_cancellations', 'previous_bookings_not_canceled',
    'reserved_room_type', 'assigned_room_type',
    'booking_changes', 'deposit_type', 'days_in_waiting_list',
    'customer_type', 'adr',
    'required_car_parking_spaces', 'total_of_special_requests'
]
X = np.array([[user_input[col] for col in features]])
prediction = model.predict(X)

print("\nPrediction Score:", prediction[0])

if prediction[0] >= 0.5:
    print(" Likely to Cancel Booking")
else:
    print(" Booking is Safe")

Enter Booking Details:

Prediction Score: 58.932413793103414
 Likely to Cancel Booking

c:\Users\Ayesha\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(