#  **Topic:** 
# <center> **Hotel Booking Cancellation Prediction** </center>

<div class="alert alert-block alert-success">
    <b>Importing required Libraries and Dataset</b> 
    <br>
   </div>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

<div class="alert alert-block alert-success">
    <h1>1. Data Reading / Data Loading</h1>
</div>

#### Dataset: <a>https://www.kaggle.com/datasets/jessemostipak/hotel-booking-demand</a>

In [2]:
import pandas as pd
Dataset = pd.read_csv('hotel_bookings.csv')
Dataset

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,36,2016,May,22,23,1,2,2,...,No Deposit,240.0,NaN,0,Transient-Party,75.00,1,1,Check-Out,26/05/2016
1,City Hotel,0,276,2016,September,39,22,0,3,1,...,No Deposit,6.0,NaN,178,Transient-Party,95.67,0,0,Check-Out,25/09/2016
2,Resort Hotel,0,32,2017,February,8,25,2,1,2,...,No Deposit,240.0,NaN,0,Transient-Party,58.00,0,2,Check-Out,28/02/2017
3,City Hotel,0,30,2017,June,23,8,1,3,2,...,No Deposit,28.0,NaN,0,Transient,89.00,0,0,Check-Out,12/06/2017
4,Resort Hotel,1,197,2016,May,22,24,0,4,2,...,No Deposit,240.0,NaN,0,Transient,65.70,0,0,Canceled,16/02/2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,Resort Hotel,0,25,2017,August,32,6,4,10,2,...,No Deposit,40.0,NaN,0,Group,114.76,0,2,Check-Out,20/08/2017
11996,Resort Hotel,0,194,2016,August,33,7,2,2,2,...,No Deposit,96.0,NaN,0,Transient,97.40,0,1,Check-Out,11/08/2016
11997,City Hotel,0,135,2016,September,40,25,2,0,3,...,No Deposit,9.0,NaN,0,Transient,162.00,0,2,Check-Out,27/09/2016
11998,Resort Hotel,0,27,2016,June,25,12,2,1,1,...,No Deposit,240.0,NaN,0,Transient,120.00,0,1,Check-Out,15/06/2016
11999,City Hotel,1,123,2017,May,20,19,0,2,2,...,No Deposit,9.0,NaN,0,Transient,126.00,0,0,Canceled,17/01/2017

<div class="alert alert-block alert-success">
    <h1>2. EDA (Data Exploration)</h1>
</div>

In [3]:
Dataset.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,36,2016,May,22,23,1,2,2,...,No Deposit,240.0,NaN,0,Transient-Party,75.00,1,1,Check-Out,26/05/2016
1,City Hotel,0,276,2016,September,39,22,0,3,1,...,No Deposit,6.0,NaN,178,Transient-Party,95.67,0,0,Check-Out,25/09/2016
2,Resort Hotel,0,32,2017,February,8,25,2,1,2,...,No Deposit,240.0,NaN,0,Transient-Party,58.00,0,2,Check-Out,28/02/2017
3,City Hotel,0,30,2017,June,23,8,1,3,2,...,No Deposit,28.0,NaN,0,Transient,89.00,0,0,Check-Out,12/06/2017
4,Resort Hotel,1,197,2016,May,22,24,0,4,2,...,No Deposit,240.0,NaN,0,Transient,65.70,0,0,Canceled,16/02/2016

In [4]:
Dataset.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
11995,Resort Hotel,0,25,2017,August,32,6,4,10,2,...,No Deposit,40.0,NaN,0,Group,114.76,0,2,Check-Out,20/08/2017
11996,Resort Hotel,0,194,2016,August,33,7,2,2,2,...,No Deposit,96.0,NaN,0,Transient,97.40,0,1,Check-Out,11/08/2016
11997,City Hotel,0,135,2016,September,40,25,2,0,3,...,No Deposit,9.0,NaN,0,Transient,162.00,0,2,Check-Out,27/09/2016
11998,Resort Hotel,0,27,2016,June,25,12,2,1,1,...,No Deposit,240.0,NaN,0,Transient,120.00,0,1,Check-Out,15/06/2016
11999,City Hotel,1,123,2017,May,20,19,0,2,2,...,No Deposit,9.0,NaN,0,Transient,126.00,0,0,Canceled,17/01/2017

## Rows & Column

In [5]:
print('rows:', Dataset.shape[0])
print('columns:', Dataset.shape[1])

rows: 12000
columns: 32

In [6]:
Dataset.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='str')

In [7]:
Dataset.shape

(12000, 32)

In [8]:
Dataset.count()

hotel                             12000
is_canceled                       12000
lead_time                         12000
arrival_date_year                 12000
arrival_date_month                12000
arrival_date_week_number          12000
arrival_date_day_of_month         12000
stays_in_weekend_nights           12000
stays_in_week_nights              12000
adults                            12000
children                          11999
babies                            12000
meal                              12000
country                           11955
market_segment                    12000
distribution_channel              12000
is_repeated_guest                 12000
previous_cancellations            12000
previous_bookings_not_canceled    12000
reserved_room_type                12000
assigned_room_type                12000
booking_changes                   12000
deposit_type                      12000
agent                             10358
company                             682
days_in_waiting_list              12000
customer_type                     12000
adr                               12000
required_car_parking_spaces       12000
total_of_special_requests         12000
reservation_status                12000
reservation_status_date           12000
dtype: int64

In [9]:
Dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           12000 non-null  str
 1   is_canceled                     12000 non-null  int64
 2   lead_time                       12000 non-null  int64
 3   arrival_date_year               12000 non-null  int64
 4   arrival_date_month              12000 non-null  str
 5   arrival_date_week_number        12000 non-null  int64
 6   arrival_date_day_of_month       12000 non-null  int64
 7   stays_in_weekend_nights         12000 non-null  int64
 8   stays_in_week_nights            12000 non-null  int64
 9   adults                          12000 non-null  int64
 10  children                        11999 non-null  float64
 11  babies                          12000 non-null  int64
 12  meal                            12000 non-null  str
 13  country                         11955 non-null  str
 14  market_segment                  12000 non-null  str
 15  distribution_channel            12000 non-null  str
 16  is_repeated_guest               12000 non-null  int64
 17  previous_cancellations          12000 non-null  int64
 18  previous_bookings_not_canceled  12000 non-null  int64
 19  reserved_room_type              12000 non-null  str
 20  assigned_room_type              12000 non-null  str
 21  booking_changes                 12000 non-null  int64
 22  deposit_type                    12000 non-null  str
 23  agent                           10358 non-null  float64
 24  company                         682 non-null    float64
 25  days_in_waiting_list            12000 non-null  int64
 26  customer_type                   12000 non-null  str
 27  adr                             12000 non-null  float64
 28  required_car_parking_spaces     12000 non-null  int64
 29  total_of_special_requests       12000 non-null  int64
 30  reservation_status              12000 non-null  str
 31  reservation_status_date         12000 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 3.8 MB

In [10]:
Dataset.nunique()

hotel                                2
is_canceled                          2
lead_time                          448
arrival_date_year                    3
arrival_date_month                  12
arrival_date_week_number            53
arrival_date_day_of_month           31
stays_in_weekend_nights             12
stays_in_week_nights                24
adults                               5
children                             4
babies                               3
meal                                 5
country                            104
market_segment                       7
distribution_channel                 5
is_repeated_guest                    2
previous_cancellations              13
previous_bookings_not_canceled      31
reserved_room_type                   9
assigned_room_type                  11
booking_changes                     10
deposit_type                         3
agent                              234
company                            162
days_in_waiting_list                84
customer_type                        4
adr                               2447
required_car_parking_spaces          4
total_of_special_requests            6
reservation_status                   3
reservation_status_date            846
dtype: int64

In [11]:
Dataset['agent'].nunique

<bound method IndexOpsMixin.nunique of 0        240.0
1          6.0
2        240.0
3         28.0
4        240.0
         ...
11995     40.0
11996     96.0
11997      9.0
11998    240.0
11999      9.0
Name: agent, Length: 12000, dtype: float64>

In [12]:
Dataset.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,11999.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,10358.000000,682.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,0.370417,101.898917,2016.154583,27.121500,15.908667,0.916167,2.501417,1.856000,0.102759,0.007500,0.030500,0.075000,0.141500,0.217917,87.066036,179.494135,2.203333,102.871718,0.063417,0.568417
std,0.482936,105.436187,0.706679,13.680588,8.802203,0.997524,1.940398,0.489167,0.395455,0.087241,0.171966,0.645815,1.477213,0.623133,110.688003,130.779008,15.506757,68.372150,0.246103,0.789011
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,47.000000,0.000000,70.000000,0.000000,0.000000
50%,0.000000,67.000000,2016.000000,27.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,169.000000,0.000000,95.000000,0.000000,0.000000
75%,1.000000,158.000000,2017.000000,38.000000,24.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,242.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,629.000000,2017.000000,53.000000,31.000000,12.000000,30.000000,4.000000,3.000000,2.000000,1.000000,26.000000,64.000000,13.000000,531.000000,525.000000,391.000000,5400.000000,3.000000,5.000000

In [13]:
Dataset.isnull().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              1
babies                                0
meal                                  0
country                              45
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                              1642
company                           11318
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

In [14]:
Dataset.dtypes

hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

<div class="alert alert-block alert-success">
    <h1>3. Data Pre-Processing</h1>
</div>

### Checking null values

In [15]:
Dataset.isnull().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              1
babies                                0
meal                                  0
country                              45
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                              1642
company                           11318
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

## Filling null values

In [16]:
num = Dataset['company'].mode()[0]
Dataset['company'] = Dataset['company'].fillna(num)

In [17]:
num = Dataset['children'].mode()[0]
Dataset['children'] = Dataset['children'].fillna(num)

In [18]:
num = Dataset['agent'].mode()[0]
Dataset['agent'] = Dataset['agent'].fillna(num)

In [19]:
num = Dataset['country'].mode()[0]
Dataset['country'] = Dataset['country'].fillna(num)

In [20]:
Dataset.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

### Check datatypes of all columns & change

In [21]:
Dataset.dtypes

hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

In [22]:
cols = ['agent', 'children', 'company']
Dataset[cols] = Dataset[cols].fillna(0).astype(int)

In [23]:
Dataset.dtypes

hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                            int64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                               int64
company                             int64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

In [24]:
columns_to_drop = ['company', 'agent', 'reservation_status', 'reservation_status_date']
Dataset.drop(columns=columns_to_drop, inplace=True)

In [25]:
Dataset.to_csv('cleaned_data.csv', index=False, header=True)

In [26]:
encoders = {}

def encodeCols(cols):
    for i in cols:
        # Har column ki unique values ka DataFrame banana
        value = pd.DataFrame({i: Dataset[i].unique()})
        LE = LabelEncoder()
        LE.fit(value[i])
        Dataset[i] = LE.transform(Dataset[i])
        encoders[i] = LE
columns_to_encode = [
    'hotel', 'arrival_date_month', 'meal', 'country', 
    'market_segment', 'distribution_channel', 'reserved_room_type', 
    'assigned_room_type', 'deposit_type', 'customer_type', 
     
]
encodeCols(columns_to_encode)
joblib.dump(encoders, "encoders.pkl")

['encoders.pkl']

In [27]:
Dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           12000 non-null  int64
 1   is_canceled                     12000 non-null  int64
 2   lead_time                       12000 non-null  int64
 3   arrival_date_year               12000 non-null  int64
 4   arrival_date_month              12000 non-null  int64
 5   arrival_date_week_number        12000 non-null  int64
 6   arrival_date_day_of_month       12000 non-null  int64
 7   stays_in_weekend_nights         12000 non-null  int64
 8   stays_in_week_nights            12000 non-null  int64
 9   adults                          12000 non-null  int64
 10  children                        12000 non-null  int64
 11  babies                          12000 non-null  int64
 12  meal                            12000 non-null  int64
 13  country                         12000 non-null  int64
 14  market_segment                  12000 non-null  int64
 15  distribution_channel            12000 non-null  int64
 16  is_repeated_guest               12000 non-null  int64
 17  previous_cancellations          12000 non-null  int64
 18  previous_bookings_not_canceled  12000 non-null  int64
 19  reserved_room_type              12000 non-null  int64
 20  assigned_room_type              12000 non-null  int64
 21  booking_changes                 12000 non-null  int64
 22  deposit_type                    12000 non-null  int64
 23  days_in_waiting_list            12000 non-null  int64
 24  customer_type                   12000 non-null  int64
 25  adr                             12000 non-null  float64
 26  required_car_parking_spaces     12000 non-null  int64
 27  total_of_special_requests       12000 non-null  int64
dtypes: float64(1), int64(27)
memory usage: 2.6 MB

<div class="alert alert-block alert-success">
    <h1>Train-Test Splitting</h1>
</div>

In [28]:
X = Dataset.drop('adr', axis=1)  
y = Dataset['adr']

In [29]:
X.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests
0,1,0,36,2016,8,22,23,1,2,2,...,0,0,0,2,0,0,0,3,1,1
1,0,0,276,2016,11,39,22,0,3,1,...,0,0,0,0,0,0,178,3,0,0
2,1,0,32,2017,3,8,25,2,1,2,...,0,0,3,3,1,0,0,3,0,2
3,0,0,30,2017,6,23,8,1,3,2,...,0,0,0,0,0,0,0,2,0,0
4,1,1,197,2016,8,22,24,0,4,2,...,0,0,3,3,0,0,0,2,0,0

In [30]:
y.head()

0    75.00
1    95.67
2    58.00
3    89.00
4    65.70
Name: adr, dtype: float64

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
X_train.head()
y_train.head()

9182     96.5
11091    88.2
6428     98.0
288      95.0
2626     75.0
Name: adr, dtype: float64

In [33]:
X_test.head()
y_test.head()

1935    130.0
6494     97.0
1720    339.4
9120     70.0
360     130.5
Name: adr, dtype: float64

In [34]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(9600, 27) (9600,)
(2400, 27) (2400,)

<div class="alert alert-block alert-success">
    <h1>Model Application</h1>
</div>

In [35]:
print("--Training the Model using Random Forest Regressor--")

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

--Training the Model using Random Forest Regressor--

RandomForestRegressor(random_state=42)

In [36]:
import pickle
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("Model Saved Successfully")

Model Saved Successfully

In [37]:
import joblib
joblib.dump(model, "model.pkl", compress=('xz', 9))

['model.pkl']

In [38]:
#Testing/Predicting
y_pred = model.predict(X_test)

In [39]:
from sklearn.metrics import mean_squared_error, r2_score

print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

504.92075614928683
0.7876088571969458

<div class="alert alert-block alert-success">
    <h1>Model Accuracy</h1>
</div>

In [40]:
print(f"Model Accuracy (R2 Score): {r2_score(y_test, y_pred):.2%}")

Model Accuracy (R2 Score): 78.76%

<div class="alert alert-block alert-success">
    <h1> Application Phase</h1>
</div>

In [41]:
import pandas as pd
import numpy as np
import pickle
import joblib

model = joblib.load('model.pkl')
encoders = joblib.load('encoders.pkl')

def encode_cols(le, value):
    if value in le.classes_:
        return le.transform([value])[0]
    else:
        return -1

print("Enter Booking Details:")

user_input = {
    "hotel": input("Hotel (Resort Hotel / City Hotel): "),
    "lead_time": int(input("Lead Time: ")),
    "arrival_date_year": int(input("Arrival Year: ")),
    "arrival_date_month": input("Arrival Month: "),
    "arrival_date_week_number": int(input("Week Number: ")),
    "arrival_date_day_of_month": int(input("Day of Month: ")),

    "stays_in_weekend_nights": int(input("Weekend Nights: ")),
    "stays_in_week_nights": int(input("Week Nights: ")),

    "adults": int(input("Adults: ")),
    "children": int(input("Children: ")),
    "babies": int(input("Babies: ")),

    "meal": input("Meal (BB/HB/FB/SC): "),
    "country": input("Country: "),
    "market_segment": input("Market Segment: "),
    "distribution_channel": input("Distribution Channel: "),

    "is_repeated_guest": int(input("Repeated Guest (0/1): ")),
    "previous_cancellations": int(input("Previous Cancellations: ")),
    "previous_bookings_not_canceled": int(input("Previous Not Canceled: ")),

    "reserved_room_type": input("Reserved Room Type: "),
    "assigned_room_type": input("Assigned Room Type: "),

    "booking_changes": int(input("Booking Changes: ")),
    "deposit_type": input("Deposit Type: "),
    "days_in_waiting_list": int(input("Waiting Days: ")),

    "customer_type": input("Customer Type: "),
    "adr": float(input("ADR (Average Daily Rate): ")),

    "required_car_parking_spaces": int(input("Parking Spaces: ")),
    "total_of_special_requests": int(input("Special Requests: "))
}

categorical_cols = [
    'hotel', 'arrival_date_month', 'meal', 'country',
    'market_segment', 'distribution_channel',
    'reserved_room_type', 'assigned_room_type',
    'deposit_type', 'customer_type'
]

for col in categorical_cols:
    user_input[col] = encode_cols(encoders[col], user_input[col])

features = [
    'hotel', 'lead_time', 'arrival_date_year', 'arrival_date_month',
    'arrival_date_week_number', 'arrival_date_day_of_month',
    'stays_in_weekend_nights', 'stays_in_week_nights',
    'adults', 'children', 'babies', 'meal', 'country',
    'market_segment', 'distribution_channel', 'is_repeated_guest',
    'previous_cancellations', 'previous_bookings_not_canceled',
    'reserved_room_type', 'assigned_room_type',
    'booking_changes', 'deposit_type', 'days_in_waiting_list',
    'customer_type', 'adr',
    'required_car_parking_spaces', 'total_of_special_requests'
]
X = np.array([[user_input[col] for col in features]])
prediction = model.predict(X)

print("\nPrediction Score:", prediction[0])

if prediction[0] >= 0.5:
    print(" Likely to Cancel Booking")
else:
    print(" Booking is Safe")

Enter Booking Details:

Prediction Score: 85.10169999999998
 Likely to Cancel Booking

c:\Users\Ayesha\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(